gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title/
paginate: 5
paginate_path: "page:num"
exclude: [vendor]

url:
baseurl:

safe: false
cdnurl: http://7xkamc.com1.z0.glb.clouddn.com

static:
  image_path: false
  public_path: false

redcarpet:
  extensions: [strikethrough, tables]

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
